platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def runtimepods
  pod 'ShiftSDK', :path => '../'
  pod 'Alamofire', '4.7.3'
  pod 'SwiftyJSON', '4.0.0'
  pod 'SnapKit', '4.0.0'
  pod 'Bond', '6.8.3'
  pod 'HTAutocompleteTextField', '1.3.2'
  pod 'GoogleKit', '0.3.2'
  pod 'PhoneNumberKit', '2.5.0'
  pod 'TTTAttributedLabel', '2.0.0'
  pod 'UIScrollView-InfiniteScroll', '1.0.2'
  pod 'TrustKit', '1.5.3'
  pod 'Stripe', '12.0.0'
  pod 'Down', '0.5.2'
  pod 'Plaid', '1.1.2'
  pod 'PullToRefreshKit', '0.8.6'
  pod 'SwiftToast', '1.1.3'
  pod 'SwiftLint'
end

target :Demo do
  runtimepods
  target 'UnitTests' do
    inherit! :search_paths
  end
  target 'AutomationTests' do
    inherit! :search_paths
    pod 'KIF', '3.6.0', :configurations => ['Local','Stg','Dev']
    pod 'Alamofire-Synchronous', '4.0.0', :configurations => ['Local','Stg','Dev']
  end
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited), PodsDummy_Pods=SomeOtherNamePodsDummy_Pods'
      if config.name == 'Local'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
      if config.name == 'Dev'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
      if config.name == 'Stg'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end
