language: objective-c
osx_image: xcode8.3
before_install:
    - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6s (9.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
    - echo $IOS_SIMULATOR_UDID
    - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
script:
    - cd Example && pod repo update && pod install && cd .. && set -o pipefail
    - travis_retry xcodebuild -scheme "Link Local" -workspace Example/LedgeLink.xcworkspace -configuration "Local" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=9.2' ARCHS="x86_64" VALID_ARCHS="x86_64" -enableCodeCoverage YES clean build test | xcpretty
    - travis_retry xcodebuild -scheme "Link Automation Tests" -workspace Example/LedgeLink.xcworkspace -configuration "Stg" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=9.2' ARCHS="x86_64" VALID_ARCHS="x86_64" test | xcpretty
after_success:
    - bash <(curl -s https://codecov.io/bash) -t 80641127-7644-4067-9c77-bfacd058fce4 -J LedgeLink