version: 2
jobs:
  build-and-test:

    macos:
      xcode: "10.0.0" # Maximum version supported

    steps:
      - checkout

      - restore_cache:
          key: deps-{{ checksum "Example/Podfile" }}

      - run:
          name: Install CocoaPods
          command: cd Example && pod install

      - save_cache:
          key: deps-{{ checksum "Example/Podfile" }}
          paths:
            - "~/.cocoapods"

      # The lane has to be replaced with "tests" as soon as we fix the Automation Tests
      - run:
          name: Build and run tests
          command: cd Example && fastlane unit_tests

      - store_artifacts:
          path: Example/fastlane/test_output

      - store_test_results:
          path: Example/fastlane/test_output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
